# Identity
peer_name: "peer_01"
key_path: "./data/keys/private_key.pem"

# Network
listen_port: 9000
discovery_timeout: 5  # seconds

# File Sharing
shared_dir: "./data/shared"
download_dir: "./data/downloads"
metadata_cache: "./data/metadata.json"
